# Generated by Django 3.1 on 2020-08-30 08:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('class_time', models.CharField(
                    max_length=20, verbose_name='Class Time')),
                ('short_desc', models.CharField(
                    max_length=256, verbose_name='Short Description')),
                ('active', models.BooleanField(
                    default=True, verbose_name='Is Active?!')),
                ('image', models.ImageField(
                    upload_to='images/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'db_table': 'kiddos_courses',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('name', models.CharField(max_length=50,
                                          primary_key=True, serialize=False, verbose_name='Name')),
                ('value', models.TextField(blank=True,
                                           max_length=512, null=True, verbose_name='Value')),
            ],
            options={
                'db_table': 'kiddos_settings',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('short_desc', models.CharField(
                    max_length=256, verbose_name='Short Description')),
                ('body', models.TextField(verbose_name='Body')),
                ('create_date', models.DateTimeField(blank=True,
                                                     default=datetime.datetime.now, verbose_name='Creation Date')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'db_table': 'kiddos_blog_post',
            },
        ),
    ]
