# Generated by Django 3.1 on 2020-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_teacher_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Facebook Account'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='googleplus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Google+ Account'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram Account'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Twitter Account'),
        ),
    ]
