# Generated by Django 3.1 on 2020-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_blogpost_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='Person')),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('note', models.TextField(verbose_name='Note')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Photo')),
            ],
            options={
                'db_table': 'kiddos_endorsement',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='publish_on_index',
            field=models.BooleanField(default=True, verbose_name='Is publishedon index page?!'),
        ),
    ]
