# Generated by Django 3.1 on 2020-08-31 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200830_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='photo/gallery/', verbose_name='Photo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published!')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'kiddos_gallery',
            },
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='publish_on_index',
            field=models.BooleanField(default=True, verbose_name='Is published on index page?!'),
        ),
    ]
