# Generated by Django 3.1 on 2020-08-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200831_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('short_desc', models.CharField(max_length=512, verbose_name='Short Description')),
                ('body', models.TextField(verbose_name='Body')),
                ('publish_on_index', models.BooleanField(default=False, verbose_name='Publish on Index page')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'db_table': 'kiddos_page',
            },
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
