# Generated by Django 3.1 on 2020-09-01 07:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200901_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuestforquote',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='reuestforquote',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reuestforquote',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is done?!'),
        ),
    ]
