# Generated by Django 3.1 on 2020-09-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200901_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('message', models.TextField(verbose_name='Message')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
            ],
            options={
                'db_table': 'kiddos_post_comment',
            },
        ),
    ]
