# Generated by Django 3.1 on 2020-09-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_postcomment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='blog_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.blogpost', verbose_name='Blog Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published!'),
        ),
    ]
