# Generated by Django 3.1 on 2020-09-06 07:40

from django.db import migrations, models
import pages.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200901_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(help_text='HTML tags can be used to decorating the text', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[pages.utils.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Enter title of blog post', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[pages.utils.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', validators=[pages.utils.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='photo/gallery/', validators=[pages.utils.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[pages.utils.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[pages.utils.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='reuestforquote',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', validators=[pages.utils.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'title', 'short_desc'], name='search_on_blog_pots'),
        ),
    ]
