# Generated by Django 3.1.3 on 2021-12-16 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200906_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('structure', models.JSONField()),
            ],
            options={
                'db_table': 'kiddos_custom_form',
            },
        ),
        migrations.CreateModel(
            name='CustomFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('list_order', models.IntegerField()),
                ('custom_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customform')),
            ],
            options={
                'db_table': 'kiddos_custom_form_data',
            },
        ),
    ]
