# Generated by Django 4.0.5 on 2022-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_customform_customformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('structure', models.TextField()),
            ],
        ),
    ]
