# Generated by Django 4.0.5 on 2022-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_elementtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtemplate',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
