# Generated by Django 4.0.5 on 2022-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_website_elementtemplate_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='subdomain',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementtemplate',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='elementtemplate',
            unique_together={('name', 'website')},
        ),
    ]
